version: '3.8'

services:

  

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: robotdb
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rescuebot-os:
    build: .
    environment:
      RABBIT_MQ_SERVER_URI: "amqp://guest:guest@rabbitmq:5672"

volumes:
  rabbitmq_data:
  postgres_data:
