version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: robotdb
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U guest"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  rescuebot-os:
    build: .
    environment:
      RABBIT_MQ_SERVER_URI: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
      # postgres:
      #   condition: service_healthy

volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
